services:
  - type: web
    name: control-escolar-api
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn control_escolar_desit_api.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: control_escolar_desit_api.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: control-escolar-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: control-escolar-api.onrender.com,*.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://tu-frontend.onrender.com,http://localhost:4200

databases:
  - name: control-escolar-db
    databaseName: control_escolar_desit_db
    user: control_escolar_user
    plan: free

